# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-19 04:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PRO_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='#', max_length=100, verbose_name='\u8f6e\u64ad\u56feURL')),
                ('image', models.ImageField(default='image/carousel.jpg', upload_to='Carousel/%Y/%m', verbose_name='\u8f6e\u64ad\u56fe')),
                ('index', models.IntegerField(default=0, verbose_name='\u5e8f\u53f7')),
                ('time_in', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8f6e\u64ad\u56fe\u8868',
                'verbose_name_plural': '\u8f6e\u64ad\u56fe\u8868',
            },
        ),
        migrations.CreateModel(
            name='LeaderFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6587\u4ef6\u540d')),
                ('words', models.CharField(max_length=200, verbose_name='\u6587\u4ef6\u63cf\u8ff0')),
                ('file', models.FileField(default='file/default.txt', upload_to='file/%Y/%m', verbose_name='\u6587\u4ef6')),
                ('done', models.BooleanField(default=0, verbose_name='\u662f\u5426\u901a\u8fc7')),
                ('time_in', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5bfc\u6e38')),
            ],
            options={
                'verbose_name': '\u5bfc\u6e38\u8d44\u6599\u5ba1\u6838\u8868',
                'verbose_name_plural': '\u5bfc\u6e38\u8d44\u6599\u5ba1\u6838\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField(default='', verbose_name='\u62c9\u7968\u5185\u5bb9')),
                ('done', models.BooleanField(default=0, verbose_name='\u662f\u5426\u901a\u8fc7')),
                ('time_do', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5904\u7406\u65f6\u95f4')),
                ('time_in', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRO_APP.Projects', verbose_name='\u7c7b\u4f3c\u9879\u76ee')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5bfc\u6e38')),
            ],
            options={
                'verbose_name': '\u63a8\u8350\u5f00\u8bbe\u9879\u76ee\u8868',
                'verbose_name_plural': '\u63a8\u8350\u5f00\u8bbe\u9879\u76ee\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click', models.IntegerField(default=0, verbose_name='\u7528\u6237\u70b9\u51fb\u6570')),
                ('like', models.BooleanField(default=0, verbose_name='\u662f\u5426\u5173\u6ce8')),
                ('time_in', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u89e6\u53d1\u65f6\u95f4')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRO_APP.Projects', verbose_name='\u9879\u76ee')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5bfc\u6e38')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6d4f\u89c8\u9879\u76ee\u8bb0\u5f55\u8868',
                'verbose_name_plural': '\u7528\u6237\u6d4f\u89c8\u9879\u76ee\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_part', models.FloatField(default=0.0, verbose_name='\u5df2\u7f34\u7eb3\u91d1\u989d')),
                ('money_left', models.FloatField(default=0.0, verbose_name='\u672a\u7f34\u7eb3\u91d1\u989d')),
                ('done', models.BooleanField(default=0, verbose_name='\u662f\u5426\u5b8c\u6210\u652f\u4ed8')),
                ('time_do', models.DateTimeField(verbose_name='\u5b8c\u6210\u652f\u4ed8\u65f6\u95f4')),
                ('time_in', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRO_APP.Projects', verbose_name='\u9879\u76ee')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5bfc\u6e38')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u8d2d\u4e70\u9879\u76ee\u8868',
                'verbose_name_plural': '\u7528\u6237\u8d2d\u4e70\u9879\u76ee\u8868',
            },
        ),
    ]
