# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-19 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPR_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='content',
            field=models.TextField(default='', verbose_name='\u516c\u544a\u5185\u5bb9'),
        ),
    ]
