# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-19 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPR_APP', '0002_carousel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='\u516c\u544a\u6807\u9898'),
        ),
    ]
