# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-23 15:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPR_APP', '0003_carousel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoney',
            name='time_do',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5b8c\u6210\u652f\u4ed8\u65f6\u95f4'),
        ),
    ]
