# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-19 04:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_A', models.IntegerField(default=0, verbose_name='A\u4eba\u6570')),
                ('num_B', models.IntegerField(default=0, verbose_name='B\u4eba\u6570')),
                ('num_C', models.IntegerField(default=0, verbose_name='C\u4eba\u6570')),
                ('num_D', models.IntegerField(default=0, verbose_name='D\u4eba\u6570')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u5206\u6790\u8868',
                'verbose_name_plural': '\u9879\u76ee\u5206\u6790\u8868',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0, verbose_name='\u7b2c\u51e0\u5929')),
                ('place', models.CharField(default='\u672a\u547d\u540d', max_length=100, verbose_name='\u5730\u70b9')),
                ('day_in', models.DateField(verbose_name='\u5230\u8fbe\u65f6\u95f4')),
                ('day_out', models.DateField(verbose_name='\u79bb\u5f00\u65f6\u95f4')),
                ('time_in', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u884c\u7a0b\u8868',
                'verbose_name_plural': '\u9879\u76ee\u884c\u7a0b\u8868',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='\u9879\u76eeID')),
                ('name', models.CharField(default='\u672a\u547d\u540d', max_length=50, verbose_name='\u9879\u76ee\u540d')),
                ('image', models.ImageField(default='image/project.jpg', upload_to='project/%Y/%m', verbose_name='\u9879\u76ee\u9996\u9875\u56fe')),
                ('description', models.CharField(default='', max_length=300, verbose_name='\u9879\u76ee\u63cf\u8ff0')),
                ('something', models.TextField(default='', verbose_name='\u9879\u76ee\u8be6\u60c5')),
                ('last', models.IntegerField(default=0, verbose_name='\u9879\u76ee\u8017\u65f6')),
                ('style', models.CharField(choices=[('1', '\u7586\u85cf'), ('2', '\u4e1c\u5317'), ('3', '\u897f\u5317'), ('4', '\u5317\u65b9'), ('5', '\u6c5f\u6d59\u6caa'), ('6', '\u5357\u65b9'), ('7', '\u6b27\u6d32'), ('8', '\u975e\u6d32'), ('9', '\u6fb3\u6d32'), ('10', '\u7f8e\u6d32'), ('11', '\u4e9a\u6d32'), ('12', '\u5f02\u57df\u98ce\u60c5')], default='register', max_length=8, verbose_name='\u7c7b\u578b')),
                ('price', models.FloatField(default=0.0, verbose_name='\u4ef7\u683c')),
                ('num_min', models.IntegerField(default=0, verbose_name='\u6700\u4f4e\u5f00\u56e2\u4eba\u6570')),
                ('num_max', models.IntegerField(default=0, verbose_name='\u6700\u591a\u4eba\u6570')),
                ('status', models.CharField(choices=[('0', '\u6a21\u578b\u56e2'), ('1', '\u8fbe\u5230\u5f00\u56e2\u4eba\u6570'), ('2', '\u63a8\u8350\u5bfc\u6e38\u4e2d'), ('3', '\u5bfc\u6e38\u6295\u7968\u4e2d'), ('4', '\u6295\u7968\u7ed3\u679c\u786e\u8ba4'), ('5', '\u6b63\u5728\u65c5\u6e38'), ('6', '\u5df2\u7ecf\u7ed3\u675f')], default='\u6a21\u578b\u56e2', max_length=10, verbose_name='\u7c7b\u578b')),
                ('num_click', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('num_admire', models.IntegerField(default=0, verbose_name='\u5173\u6ce8\u6570')),
                ('time_in', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u57fa\u672c\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u9879\u76ee\u57fa\u672c\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='TimeLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('1', '\u8fbe\u5230\u5f00\u56e2\u4eba\u6570'), ('2', '\u63a8\u8350\u5bfc\u6e38\u4e2d'), ('3', '\u5bfc\u6e38\u6295\u7968\u4e2d'), ('4', '\u6295\u7968\u7ed3\u679c\u786e\u8ba4')], default='\u6a21\u578b\u56e2', max_length=10, verbose_name='\u65f6\u95f4\u7c7b\u578b')),
                ('time_start', models.DateTimeField(verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('time_end', models.DateTimeField(verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('time_in', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u622a\u6b62\u65e5\u671f\u8868',
                'verbose_name_plural': '\u9879\u76ee\u622a\u6b62\u65e5\u671f\u8868',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRO_APP.Projects', verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRO_APP.Projects', verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
    ]
