# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-19 04:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('USER_APP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PRO_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0, verbose_name='\u7968\u6570')),
                ('words', models.TextField(default='', verbose_name='\u62c9\u7968\u5185\u5bb9')),
                ('done_one', models.BooleanField(default=0, verbose_name='\u662f\u5426\u4e3a\u6700\u7ec8\u5bfc\u6e38')),
                ('done_two', models.BooleanField(default=0, verbose_name='\u662f\u5426\u4e3a\u540e\u5907\u5bfc\u6e38')),
                ('time_in', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USER_APP.Leader', verbose_name='\u5bfc\u6e38')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRO_APP.Projects', verbose_name='\u9879\u76ee')),
            ],
            options={
                'verbose_name': '\u5bfc\u6e38\u8ba1\u7968\u8868',
                'verbose_name_plural': '\u5bfc\u6e38\u8ba1\u7968\u8868',
            },
        ),
        migrations.CreateModel(
            name='LeadeWho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=0, verbose_name='\u662f\u5426\u63a5\u53d7')),
                ('time_do', models.DateTimeField(verbose_name='\u63a5\u53d7\u65f6\u95f4')),
                ('time_in', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRO_APP.Projects', verbose_name='\u9879\u76ee')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5bfc\u6e38')),
            ],
            options={
                'verbose_name': '\u53c2\u56e2\u63a8\u8350\u5bfc\u6e38\u8868',
                'verbose_name_plural': '\u53c2\u56e2\u63a8\u8350\u5bfc\u6e38\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=0, verbose_name='\u662f\u5426\u5b8c\u6210')),
                ('feel', models.IntegerField(default=0, verbose_name='\u7528\u6237\u6e38\u73a9\u611f\u53d7\u7ea7\u522b')),
                ('words', models.TextField(verbose_name='\u7528\u6237\u6e38\u73a9\u611f\u53d7\u5185\u5bb9')),
                ('time_in', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRO_APP.Projects', verbose_name='\u9879\u76ee')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u9879\u76ee\u53c2\u4e0e\u8868',
                'verbose_name_plural': '\u7528\u6237\u9879\u76ee\u53c2\u4e0e\u8868',
            },
        ),
        migrations.CreateModel(
            name='VoteWho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=0, verbose_name='\u662f\u5426\u63a5\u53d7\u6295\u7968\u7ed3\u679c')),
                ('time_in', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6295\u7968\u65f6\u95f4')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leader', to=settings.AUTH_USER_MODEL, verbose_name='\u5bfc\u6e38')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_username', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u6e38\u5ba2\u6295\u7968\u8868',
                'verbose_name_plural': '\u6e38\u5ba2\u6295\u7968\u8868',
            },
        ),
    ]
